packages:
  - packages/*
  - playground/*

catalog:
  unbuild: ^3.6.1
  "@types/node": ^22.18.0
  typescript: ^5.9.3
  "@antfu/eslint-config": ^6.0.0
  eslint: ^9.38.0

catalogs:
  test:
    "@vitest/coverage-istanbul": ^4.0.1
    "@vitest/ui": ^4.0.1
    vitest: ^4.0.1
